- name: reload_systemd
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: promisc

- name: netplan_apply
  command: sudo netplan apply
  become: true
  async: 100
  poll: 0
